
package clases;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import static java.awt.Font.PLAIN;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.commons.codec.digest.DigestUtils;

public class Login extends javax.swing.JFrame {

    Imagen imagen = new Imagen();
    Informacion Inf;
    MySqlConn objConn = new MySqlConn();
    Clip sonido;
    
    public Login() {
        this.setContentPane(imagen);
        initComponents();
        Configuracion();
        Inf = new Informacion();
        Inf.setVisible(true);
        this.jLabelImgUser.requestFocus();
    }
    
    private void Configuracion(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/imagenes/login/Icono.png")));
        setResizable(false);
        setLocationRelativeTo(null);// Posicionar pantalla en el centro.
        setLocation(getLocation().x+230, getLocation().y);
        try {// **************************** Cargamos los sonidos o musica *********************************
            sonido = AudioSystem.getClip();
            sonido.open(AudioSystem.getAudioInputStream(new File("src\\audio\\Musica.wav")));
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
            JOptionPane.showMessageDialog(this, "Error no se pudo abrir el archivo");
        }
        sonido.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonEntrar = new javax.swing.JButton();
        jLabelImgUser = new javax.swing.JLabel();
        jLabelImgPass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanelLogin.setBackground(new java.awt.Color(24, 38, 76));
        jPanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsuario.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario");
        jLabelUsuario.setEnabled(false);
        jPanelLogin.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jTextFieldUsuario.setBackground(new java.awt.Color(24, 38, 76));
        jTextFieldUsuario.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusLost(evt);
            }
        });
        jTextFieldUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldUsuarioMouseEntered(evt);
            }
        });
        jPanelLogin.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 170, -1));
        jPanelLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 200, 10));

        jLabelPassword.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Contraseña");
        jLabelPassword.setEnabled(false);
        jPanelLogin.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jPasswordFieldPassword.setBackground(new java.awt.Color(24, 38, 76));
        jPasswordFieldPassword.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jPasswordFieldPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPasswordFieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldPasswordFocusLost(evt);
            }
        });
        jPasswordFieldPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordFieldPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPasswordFieldPasswordMouseEntered(evt);
            }
        });
        jPasswordFieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldPasswordKeyPressed(evt);
            }
        });
        jPanelLogin.add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 170, 24));
        jPanelLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 200, 10));

        jButtonEntrar.setBackground(new java.awt.Color(24, 38, 76));
        jButtonEntrar.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14), new java.awt.Color(24, 38, 76))); // NOI18N
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 290, 32));

        jLabelImgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login/User.png"))); // NOI18N
        jPanelLogin.add(jLabelImgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 50, 60));

        jLabelImgPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login/Key.png"))); // NOI18N
        jPanelLogin.add(jLabelImgPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 50, 50));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login in");
        jPanelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(542, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioMouseClicked
        this.jLabelUsuario.setVisible(false);
    }//GEN-LAST:event_jTextFieldUsuarioMouseClicked

    private void jTextFieldUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusLost
        if (this.jTextFieldUsuario.getText().trim().equals("")) {
            this.jLabelUsuario.setVisible(true);
        }
    }//GEN-LAST:event_jTextFieldUsuarioFocusLost

    private void jTextFieldUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusGained
        this.jLabelUsuario.setVisible(false);
    }//GEN-LAST:event_jTextFieldUsuarioFocusGained

    private void jPasswordFieldPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordMouseClicked
        this.jLabelPassword.setVisible(false);
    }//GEN-LAST:event_jPasswordFieldPasswordMouseClicked

    private void jPasswordFieldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordFocusLost
        String pass = new String(this.jPasswordFieldPassword.getPassword());
        if (pass.equals("")){
            this.jLabelPassword.setVisible(true);
        }
    }//GEN-LAST:event_jPasswordFieldPasswordFocusLost

    private void jPasswordFieldPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordMouseEntered
        
    }//GEN-LAST:event_jPasswordFieldPasswordMouseEntered

    private void jTextFieldUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioMouseEntered
        
    }//GEN-LAST:event_jTextFieldUsuarioMouseEntered

    private void jPasswordFieldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordFocusGained
        this.jLabelPassword.setVisible(false);
    }//GEN-LAST:event_jPasswordFieldPasswordFocusGained

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        Comprobar();
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jPasswordFieldPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Comprobar();
        }
    }//GEN-LAST:event_jPasswordFieldPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImgPass;
    private javax.swing.JLabel jLabelImgUser;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
    
        class Imagen extends javax.swing.JPanel {

        private Image Logo,Fondo,Fondo2;
        @Override
        public void paint(Graphics grafico){
                Dimension height = getSize();

                Fondo = new ImageIcon(getClass().getResource("/imagenes/login/fondo.jpg")).getImage();
                grafico.drawImage(Fondo, 0, 0, height.width, height.height,this);
                
                Fondo2 = new ImageIcon(getClass().getResource("/imagenes/login/part.gif")).getImage();
                grafico.drawImage(Fondo2, height.width/2-50, 0, height.width/2, height.height,this);
                
                Logo = new ImageIcon(getClass().getResource("/imagenes/login/logo.png")).getImage();
                grafico.drawImage(Logo, (height.width/2)-100, (height.height/2)-250, 550, 380,this);
                
                Graphics2D text = (Graphics2D) grafico;
                
                text.setColor(Color.WHITE);
                text.setFont(new Font("Nirmala UI",1,20));
                text.drawString("As Good as Gucci can get", 520, 450);
                
                setOpaque(false);
                super.paint(grafico);
        }
    }
        
    private void Comprobar(){
        String cuenta, contraseña,query;
        cuenta = this.jTextFieldUsuario.getText().trim();
        query = "select * from cuentas where cuenta = "+"'"+cuenta+"'";
        this.objConn.Consult(query);
        try{
            String contraseñaMYSql = this.objConn.rs.getString(2);
            char[] passw = this.jPasswordFieldPassword.getPassword();
            contraseña = new String(passw);
            String contraseñaencriptada = DigestUtils.md5Hex(contraseña);
            if (contraseñaMYSql.equals(contraseñaencriptada)) {
                    new Sistema(this.jTextFieldUsuario.getText(),objConn).setVisible(true);
                    sonido.stop();
                    Inf.setVisible(false);
                    this.setVisible(false);
            }
            else JOptionPane.showMessageDialog(this, "Error en la contraseña");
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "No existe la cuenta.");
            System.out.println("No existe la cuenta.");
        }
    }
}
