package clases;

import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;

public class Sistema extends javax.swing.JFrame {

    private int aux;
    Clip sonido;
    Clip sonido2;
    MySqlConn conn;

    public Sistema() {
        initComponents();
        Configuracion();
    }

    public Sistema(String usuario, MySqlConn conn) {
        this.conn = conn;   // Cargamos la base de datos para poder usarla.
        initComponents();
        this.jLabelUsuario.setText(usuario); // Mostramos quien inicio sesion.
        Configuracion();
    }

    private void Configuracion() { // Configuracion es el acomodo de todas las variables y tamaños que deamos al iniciar el sistema.
        setLocationRelativeTo(null);// Posicionar pantalla en el centro.
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/imagenes/login/Icono.png")));// Cambiar icono de ventana.
        try {// **************************** Cargamos los sonidos o musica *********************************
            sonido = AudioSystem.getClip();
            sonido.open(AudioSystem.getAudioInputStream(new File("src/audio/sonido2.wav")));
            sonido2 = AudioSystem.getClip();
            sonido2.open(AudioSystem.getAudioInputStream(new File("src/audio/sonido1.wav")));
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
            JOptionPane.showMessageDialog(this, "Error no se pudo abrir el archivo");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPlantilla = new javax.swing.ButtonGroup();
        jPanelMenu = new javax.swing.JPanel();
        jPanelUsuario = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jLabelRegistro = new javax.swing.JLabel();
        jLabelSalida = new javax.swing.JLabel();
        jLabelConsulta = new javax.swing.JLabel();
        jPanel2Localizacion = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelIconUser = new javax.swing.JLabel();
        jLabelGanancias = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Gucci Gucci");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(20, 45, 87));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelUsuario.setBackground(new java.awt.Color(23, 50, 97));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sistema/Logo_2.png"))); // NOI18N
        jLabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelUsuarioLayout = new javax.swing.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabelLogo)
                .addGap(35, 35, 35))
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelMenu.add(jPanelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 90));

        jLabelSalir.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabelSalir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalir.setText("Salir");
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseClicked(evt);
            }
        });
        jPanelMenu.add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 230, 50));

        jLabelRegistro.setBackground(new java.awt.Color(20, 45, 87));
        jLabelRegistro.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabelRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sistema/Entrada.png"))); // NOI18N
        jLabelRegistro.setText("     Entrada            ");
        jLabelRegistro.setOpaque(true);
        jLabelRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelRegistroMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelRegistroMouseReleased(evt);
            }
        });
        jPanelMenu.add(jLabelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, 60));

        jLabelSalida.setBackground(new java.awt.Color(20, 45, 87));
        jLabelSalida.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabelSalida.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sistema/Salida.png"))); // NOI18N
        jLabelSalida.setText("     Salida              ");
        jLabelSalida.setOpaque(true);
        jLabelSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSalidaMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelSalidaMouseReleased(evt);
            }
        });
        jPanelMenu.add(jLabelSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 60));

        jLabelConsulta.setBackground(new java.awt.Color(20, 45, 87));
        jLabelConsulta.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabelConsulta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sistema/Consulta.png"))); // NOI18N
        jLabelConsulta.setText("     Consulta          ");
        jLabelConsulta.setOpaque(true);
        jLabelConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConsultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelConsultaMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelConsultaMouseReleased(evt);
            }
        });
        jPanelMenu.add(jLabelConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 60));

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jPanel2Localizacion.setBackground(new java.awt.Color(45, 60, 109));

        jLabelUsuario.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario");

        jLabelIconUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sistema/user.png"))); // NOI18N

        jLabelGanancias.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabelGanancias.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGanancias.setText("Ganancias:");

        javax.swing.GroupLayout jPanel2LocalizacionLayout = new javax.swing.GroupLayout(jPanel2Localizacion);
        jPanel2Localizacion.setLayout(jPanel2LocalizacionLayout);
        jPanel2LocalizacionLayout.setHorizontalGroup(
            jPanel2LocalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2LocalizacionLayout.createSequentialGroup()
                .addContainerGap(615, Short.MAX_VALUE)
                .addComponent(jLabelIconUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2LocalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2LocalizacionLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelUsuario))
                    .addGroup(jPanel2LocalizacionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelGanancias)))
                .addGap(30, 30, 30))
        );
        jPanel2LocalizacionLayout.setVerticalGroup(
            jPanel2LocalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2LocalizacionLayout.createSequentialGroup()
                .addGroup(jPanel2LocalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2LocalizacionLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelGanancias))
                    .addGroup(jPanel2LocalizacionLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelIconUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2Localizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 780, 90));

        jPanelHome.setBackground(new java.awt.Color(0, 0, 0));
        jPanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sistema/logo.png"))); // NOI18N
        jPanelHome.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 48, -1, -1));

        getContentPane().add(jPanelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 780, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //----------------------  Eventos para Panel Registros -------------------------------

    private void jLabelRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistroMouseEntered
        if (aux != 1) {
            this.jLabelRegistro.setBackground(new java.awt.Color(26, 59, 115));
            sonido.start();
            sonido.setFramePosition(0);
        }
    }//GEN-LAST:event_jLabelRegistroMouseEntered

    private void jLabelSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalidaMouseEntered
        if (aux != 2) {
            this.jLabelSalida.setBackground(new java.awt.Color(26, 59, 115));
            sonido.start();
            sonido.setFramePosition(0);
        }
    }//GEN-LAST:event_jLabelSalidaMouseEntered

    private void jLabelConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConsultaMouseEntered
        if (aux != 3) {
            this.jLabelConsulta.setBackground(new java.awt.Color(26, 59, 115));
            sonido.start();
            sonido.setFramePosition(0);
        }
    }//GEN-LAST:event_jLabelConsultaMouseEntered

    private void jLabelRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistroMouseExited
        if (aux != 1) {
            this.jLabelRegistro.setBackground(new java.awt.Color(20, 45, 87));
            sonido.stop();
            sonido2.stop();
            sonido2.setFramePosition(0);
        }
    }//GEN-LAST:event_jLabelRegistroMouseExited

    private void jLabelSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalidaMouseExited
        if (aux != 2) {
            this.jLabelSalida.setBackground(new java.awt.Color(20, 45, 87));
            sonido.stop();
            sonido2.stop();
            sonido2.setFramePosition(0);
        }
    }//GEN-LAST:event_jLabelSalidaMouseExited

    private void jLabelConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConsultaMouseExited
        if (aux != 3) {
            this.jLabelConsulta.setBackground(new java.awt.Color(20, 45, 87));
            sonido.stop();
            sonido2.stop();
            sonido2.setFramePosition(0);
        }
    }//GEN-LAST:event_jLabelConsultaMouseExited

    private void jLabelRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistroMouseClicked

            this.jLabelSalida.setBackground(new java.awt.Color(20, 45, 87));
            this.jLabelConsulta.setBackground(new java.awt.Color(20, 45, 87));
            this.jLabelRegistro.setBackground(new java.awt.Color(74, 98, 175));
            sonido2.start();
            sonido2.setFramePosition(0);
            this.jPanelHome.setVisible(false);
            aux = 1;
    }//GEN-LAST:event_jLabelRegistroMouseClicked

    private void jLabelSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalidaMouseClicked
        aux = 2;
        this.jLabelRegistro.setBackground(new java.awt.Color(20, 45, 87));
        this.jLabelConsulta.setBackground(new java.awt.Color(20, 45, 87));
        this.jLabelSalida.setBackground(new java.awt.Color(74, 98, 175));
        sonido2.start();
        sonido2.setFramePosition(0);
        this.jPanelHome.setVisible(false);
    }//GEN-LAST:event_jLabelSalidaMouseClicked

    private void jLabelConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConsultaMouseClicked
        aux = 3;
        this.jLabelRegistro.setBackground(new java.awt.Color(20, 45, 87));
        this.jLabelSalida.setBackground(new java.awt.Color(20, 45, 87));
        this.jLabelConsulta.setBackground(new java.awt.Color(74, 98, 175));
        sonido2.start();
        sonido2.setFramePosition(0);
        this.jPanelHome.setVisible(false);
    }//GEN-LAST:event_jLabelConsultaMouseClicked

    private void jLabelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoMouseClicked
        aux = 0;
        this.jLabelSalida.setBackground(new java.awt.Color(20, 45, 87));
        this.jLabelConsulta.setBackground(new java.awt.Color(20, 45, 87));
        this.jLabelRegistro.setBackground(new java.awt.Color(20, 45, 87));
        this.jPanelHome.setVisible(true);
    }//GEN-LAST:event_jLabelLogoMouseClicked

    private void jLabelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseClicked
        System.exit(1);
    }//GEN-LAST:event_jLabelSalirMouseClicked

    private void jLabelRegistroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistroMouseReleased
            this.jLabelSalida.setBackground(new java.awt.Color(20, 45, 87));
            this.jLabelConsulta.setBackground(new java.awt.Color(20, 45, 87));
            this.jLabelRegistro.setBackground(new java.awt.Color(74, 98, 175));
            sonido2.start();
            sonido2.setFramePosition(0);
            this.jPanelHome.setVisible(false);
            aux = 1;
    }//GEN-LAST:event_jLabelRegistroMouseReleased

    private void jLabelSalidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalidaMouseReleased
        aux = 2;
        this.jLabelRegistro.setBackground(new java.awt.Color(20, 45, 87));
        this.jLabelConsulta.setBackground(new java.awt.Color(20, 45, 87));
        this.jLabelSalida.setBackground(new java.awt.Color(74, 98, 175));
        sonido2.stop();
        this.jPanelHome.setVisible(false);
    }//GEN-LAST:event_jLabelSalidaMouseReleased

    private void jLabelConsultaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConsultaMouseReleased
        aux = 3;
        this.jLabelRegistro.setBackground(new java.awt.Color(20, 45, 87));
        this.jLabelSalida.setBackground(new java.awt.Color(20, 45, 87));
        this.jLabelConsulta.setBackground(new java.awt.Color(74, 98, 175));
        sonido2.stop();
        this.jPanelHome.setVisible(false);
    }//GEN-LAST:event_jLabelConsultaMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPlantilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelConsulta;
    private javax.swing.JLabel jLabelGanancias;
    private javax.swing.JLabel jLabelIconUser;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabelSalida;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel2Localizacion;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelUsuario;
    // End of variables declaration//GEN-END:variables

}
