
package clases;

import java.awt.Font;
import java.awt.Toolkit;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.SwingConstants;

public class Voucher extends javax.swing.JFrame {

    private Huesped huesped;
    private Font font;
    
    public Voucher() {
        initComponents();
        setLocationRelativeTo(null);// Posicionar pantalla en el centro.
        setResizable(false);
    }
    
    public Voucher(Huesped persona) {
        this.huesped = persona;
        initComponents();
        setLocationRelativeTo(null);// Posicionar pantalla en el centro.
        setResizable(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/imagenes/login/Icono.png")));// Cambiar icono de ventana.
        ConfiguracionLabels();
    }
    
    public void ConfiguracionLabels(){  // Acomoda toda la informacion optenida en el objeto de la clase Huesped. para mostrarla con JLabels.
        this.jLabelNombreH.setFont(fuente(0, 11));
        this.jLabelCiudad.setFont(fuente(0, 11));
        this.jLabelFechaIng.setFont(fuente(0, 11));
        this.jLabelFechaSal.setFont(fuente(0, 11));
        this.jLabelNumeroHYPiso.setFont(fuente(0, 11));
        this.jLabelTipoYLimite.setFont(fuente(0, 11));
        this.jLabelTotalPersonas.setFont(fuente(0,11));
        this.jLabelExtras.setFont(fuente(0, 11));
        this.jLabelRegistroCompleto.setFont(fuente(0, 11));
        this.jLabelUbicacion1.setFont(fuente(0, 11));
        this.jLabelUbicacion2.setFont(fuente(0, 11));
        this.jLabelUbicacion3.setFont(fuente(0, 11));
        
        SimpleDateFormat Formato = new SimpleDateFormat("dd-MM-YYYY");
        
         this.jLabelNombreH.setText("NOMBRE DEL HUESPED: ------------ "+huesped.getNombre());
          this.jLabelCiudad.setText("CIUDAD DE ORIGEN: --------------- "+huesped.getCiudadOrigen());
        this.jLabelFechaIng.setText("FECHA DE INGRESO: --------------- "+Formato.format(huesped.getFechaIngreso()));
        
        Calendar aux = Calendar.getInstance();
        aux.setTime(huesped.getFechaIngreso());
        aux.add(Calendar.DATE, huesped.getDiasAlojo());
        this.jLabelFechaSal.setText("FECHA DE SALIDA: ---------------- "+Formato.format(aux.getTime()));
        int piso;
        if(huesped.getNumeroHabitacion()<=15) piso=1;else piso=2;
        this.jLabelNumeroHYPiso.setText("NUMERO DE HABITACION:  "+huesped.getNumeroHabitacion()+"   PISO: "+piso);
        switch(huesped.getTipoHabitacion()){
            case 'S':{
                this.jLabelTipoYLimite.setText("TIPO DE HABITACION:  Simple   (LIMITE 3 HUESPEDES)");
                if (huesped.getTotalPersonas()>1) {
                    if(huesped.getTotalPersonas()==2){
                        this.jLabelExtras.setText("1 Persona Extra.");
                    }
                    else{
                        this.jLabelExtras.setText("2 Personas Extra.");
                    }
                }
                else{
                    this.jLabelExtras.setVisible(false);
                }
                break;
            }
            case 'D':{
                this.jLabelTipoYLimite.setText("TIPO DE HABITACION:     Doble       (LIMITE 4 HUESPEDES)");
                if (huesped.getTotalPersonas()>2) {
                    if(huesped.getTotalPersonas()==3){
                        this.jLabelExtras.setText("1 Persona Extra.");
                    }
                    else{
                        this.jLabelExtras.setText("2 Personas Extra.");
                    }
                }
                else{
                    this.jLabelExtras.setVisible(false);
                }
                break;
            }
            case 'T':{
                this.jLabelTipoYLimite.setText("TIPO DE HABITACION:     Triple      (LIMITE 5 HUESPEDES)");
                if (huesped.getTotalPersonas()>3) {
                    if(huesped.getTotalPersonas()==4){
                        this.jLabelExtras.setText("1 Persona Extra.");
                    }
                    else{
                        this.jLabelExtras.setText("2 Personas Extra.");
                    }
                }
                else{
                    this.jLabelExtras.setVisible(false);
                }
                break;
            }
        }
        this.jLabelTotalPersonas.setText("TOTAL DE OCUPANTES EN LA HABITACION:      "+huesped.getTotalPersonas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLogoYNombre = new javax.swing.JLabel();
        jLabelNombreH = new javax.swing.JLabel();
        jLabelCiudad = new javax.swing.JLabel();
        jLabelFechaIng = new javax.swing.JLabel();
        jLabelFechaSal = new javax.swing.JLabel();
        jLabelNumeroHYPiso = new javax.swing.JLabel();
        jLabelTipoYLimite = new javax.swing.JLabel();
        jLabelTotalPersonas = new javax.swing.JLabel();
        jLabelExtras = new javax.swing.JLabel();
        jLabelRegistroCompleto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelUbicacion1 = new javax.swing.JLabel();
        jLabelUbicacion2 = new javax.swing.JLabel();
        jLabelUbicacion3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabelLogoYNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoYNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sistema/LogoVoucher.png"))); // NOI18N
        jLabelLogoYNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelNombreH.setText("NOMBRE DEL HUESPED:_______________");

        jLabelCiudad.setText("CIUDAD DE ORIGEN:________________");

        jLabelFechaIng.setText("FECHA DE INGRESO:________________");

        jLabelFechaSal.setText("FECHA DE SALIDA:________________");

        jLabelNumeroHYPiso.setText("NUMERO DE HABITACION: _______ PISO: _______");

        jLabelTipoYLimite.setText("TIPO DE HABITACION:______ (LIMITE___ HUESPED)");

        jLabelTotalPersonas.setText("TOTAL DE OCUPANTES EN LA HABITACION:________");

        jLabelExtras.setText("EXTRAS");

        jLabelRegistroCompleto.setText("REGISTRO COMPLETADO.");

        jButton1.setBackground(new java.awt.Color(223, 25, 25));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1)
        );

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel1.setText("As Good as Gucci can get");

        jLabelUbicacion1.setText("CALLE: Ocean Dr # 600.");

        jLabelUbicacion2.setText("CIUDAD: Miami Beach.");

        jLabelUbicacion3.setText("ESTADO: Florida(FL 33139), Estados Unidos.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelLogoYNombre)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(114, 114, 114))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUbicacion3)
                    .addComponent(jLabelUbicacion2)
                    .addComponent(jLabelUbicacion1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelCiudad)
                        .addComponent(jLabelNombreH)
                        .addComponent(jLabelFechaIng)
                        .addComponent(jLabelFechaSal)
                        .addComponent(jLabelNumeroHYPiso)
                        .addComponent(jLabelTipoYLimite)
                        .addComponent(jLabelTotalPersonas)
                        .addComponent(jLabelExtras)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRegistroCompleto)
                            .addGap(88, 88, 88))
                        .addComponent(jSeparator2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLogoYNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUbicacion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUbicacion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUbicacion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNombreH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCiudad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFechaIng)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFechaSal)
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNumeroHYPiso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTipoYLimite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTotalPersonas)
                .addGap(12, 12, 12)
                .addComponent(jLabelExtras)
                .addGap(40, 40, 40)
                .addComponent(jLabelRegistroCompleto)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();// cierra la venta y no el sistema completo.
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voucher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelExtras;
    private javax.swing.JLabel jLabelFechaIng;
    private javax.swing.JLabel jLabelFechaSal;
    private javax.swing.JLabel jLabelLogoYNombre;
    private javax.swing.JLabel jLabelNombreH;
    private javax.swing.JLabel jLabelNumeroHYPiso;
    private javax.swing.JLabel jLabelRegistroCompleto;
    private javax.swing.JLabel jLabelTipoYLimite;
    private javax.swing.JLabel jLabelTotalPersonas;
    private javax.swing.JLabel jLabelUbicacion1;
    private javax.swing.JLabel jLabelUbicacion2;
    private javax.swing.JLabel jLabelUbicacion3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
    private Font fuente(int estilo, float tamanio){ // Cargar la Funte para usarla en el Voucher.
         try {
            InputStream is =  getClass().getResourceAsStream("/librerias/FunteTiquet.ttc");
            font = Font.createFont(Font.TRUETYPE_FONT, is);
        } catch (Exception ex) {
            //Si existe un error se carga fuente por defecto ARIAL
            System.err.println("FunteTiquet.ttc" + " No se cargo la fuente");
            font = new Font("Arial", Font.PLAIN, 20);            
        }
        Font tfont = font.deriveFont(estilo, tamanio);
        return tfont;
    }
}
